### ISSUE TITLE
[BUG] device name ignored for Spotify and cannot stream to specific device with multiple devices on the same network

### ISSUE THREAD

**Issue by aofc** [mikejgray/skill-mark2-audio-receiver#15]
### Description

I own two Mycroft Mark II devices. I would like to use both of them to stream music from Spotify (ideally as a pair of speakers, but let's leave that for now). 

However, only one of the two devices get discovered, randomly. Moreover the name displayed in Spotify is Neon Mark 2, despite having set a (different) custom name for both devices in settings.json through the option "raspotify_name". Looks like this setting is ignored and I believe it is part of the problem why I see only one device.

I can stream to the (discovered) device just fine, but I can't choose which one of them.

### Steps to Reproduce

Stream music from Spotify to a Mark II device when there is more than one on the same network.

**Comment by mikejgray** [comment]
Hi @aofc , thank you for reaching out. It appears that while I set the property to read from the settings.json file, it does not actually update that file on skill load/file write. I'll get that corrected.

In the meantime, have you tried using the voice intent to set the name? "Rename Spotify device" should trigger a verbal request to change the name, which will then display what it heard you say and give you opportunities to correct it. That's how I set my multiple devices.

**Comment by aofc** [comment]
I tried what you said, it didn't work. The name did change in the config files, but I still have only one device in Spotify, advertised as Neon Mark 2.

**Comment by mikejgray** [comment]
> I tried what you said, it didn't work. The name did change in the config files, but I still have only one device in Spotify, advertised as Neon Mark 2.

I'm doing some local testing of a fix on this now. I'm curious though - what do you see in `~/logs/admin.log`? The skill is responsible for emitting the bus message that tells a plugin to update the name. I'm wondering if the bug might not actually be in the plugin.

**Comment by mikejgray** [comment]
As it turns out, both the skill and the plugin needed some adjustments, but the fixes I'm proposing should work. I would anticipate them to be in an alpha version of Neon soon - possibly as early as today or tomorrow if I can get them reviewed in time. 🙂 

Thank you so much for reporting this! I'm glad you're otherwise finding this functionality useful.

**Comment by aofc** [comment]
I'll test that as soon as I can then. 

But in the meantime, I didn't use spotify for a few days and just noticed that one of my Mark II got renamed successfully, well almost. I guess I had to restart the services or reboot it for the change to take effect and didn't notice until now. Although it was supposed to be named "neon bedroom", it is advertised as "neonbedroom".  Tried changing the name again in the settings.json file of the skill, at least trying to capitalize it, it didn't work either despite restarting. It's still all lowercase and no space, but in the settings file it had a space. You say there's a plugin involved as well, I'm wondering where the device name is actually stored?

But the good thing is it solved my other issue: not being able to play to both devices. Now that one of them has a different name, I can see both devices in Spotify.

**Comment by mikejgray** [comment]
> I'll test that as soon as I can then. 
> 
> 
> 
> But in the meantime, I didn't use spotify for a few days and just noticed that one of my Mark II got renamed successfully, well almost. I guess I had to restart the services or reboot it for the change to take effect and didn't notice until now. Although it was supposed to be named "neon bedroom", it is advertised as "neonbedroom".  Tried changing the name again in the settings.json file of the skill, at least trying to capitalize it, it didn't work either despite restarting. It's still all lowercase and no space, but in the settings file it had a space. You say there's a plugin involved as well, I'm wondering where the device name is actually stored?
> 
> 
> 
> But the good thing is it solved my other issue: not being able to play to both devices. Now that one of them has a different name, I can see both devices in Spotify.

The settings.json file is where the name is stored. I added code to this skill that sends an update request to the plugin at runtime, and a section to the plugin that restarts the service. That should take care of some of what you've described.

As for the missing spaces, that was a deliberate design decision. IIRC Spotify behaves unpredictably if you include spaces. Capitalizing it in the settings.json file, with the new updates, should behave as expected.

Thanks for your patience and for calling out this gap!

**Comment by mikejgray** [comment]
@aofc Very old issue, sorry to revive, but did the PRs resolve your issue? If so I'll go ahead and close this.

**Comment by aofc** [comment]
yes it did. you can close this
